version: '3.8'

services:
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: adminadmin
      MINIO_ROOT_PASSWORD: adminadmin
      MINIO_ACCESS_KEY: adminadmin
      MINIO_SECRET_KEY: adminadmin
    volumes:
      - minio_data:/data  # Create a named volume for Minio's object storage data
      - /home/bossnorrawich/workspace/test_datahub/dataset:/dataset  # Mount outside /data

    command: server /data --console-address ":9001"
    networks:
    - my_network  # Assign the minio container to the custom network
  
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Named volume for PostgreSQL data persistence
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql  # Initialize the DB with data
    networks:
    - my_network  # Assign the minio container to the custom network

volumes:
  db_data:  # Named volume for PostgreSQL data persistence
  minio_data:  # Named volume for Minio object storage data persistence

# Define the custom network
networks:
  my_network:
    driver: bridge